# Netlify Configuration
# Build settings for React app

[build]
  # Directory where the build happens
  base = "chatbot-demo"
  
  # Build command
  command = "npm run build"
  
  # Directory to publish (output)
  publish = "build"
  
  # Serverless functions directory
  functions = "netlify/functions"

# Environment variables (set these in Netlify dashboard)
# REACT_APP_API_URL = "https://your-backend-url/api"

# Redirect all requests to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
